modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="derecs_double_jump"
version="1.0.0"
displayName="Derec's Double Jump"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="noi01, MCreator"

[[dependencies.derecs_double_jump]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




