org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.java.installations.auto-download=false
org.gradle.java.installations.paths=C:\\Users\\DerexXD\\.jdks\\jdk-17.0.20.1+1,C:\\Users\\DerexXD\\.jdks\\jdk-21.0.12.1+1

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
neo_version=1.20.1-47.1.106
forge_version=47.1.106
forge_version_range=[47.1.106,)
loader_version_range=[47,)

mod_id=derecs_double_jump
mod_name=Derec's Double Jump
mod_license=Academic Free License v3.0
mod_version=1.0.0
mod_group_id=net.derecsdoublejump
mod_authors=Derec_
mod_description=Double jump in midair and shallow water. Jumps respect hunger and can be configured with gamerules.
